### ISSUE TITLE
Error with postgres 9.6beta3

### ISSUE THREAD

**Issue by svsool** [pgroonga/pgroonga#17]
Hi, I use postgres 9.6beta3 and get error:

```
pgroonga: failed to create database: <pg_tblspc/0/PG_9.6_201607071/0/pgrn>: system call error: No such file or directory: failed to open file info path: <pg_tblspc/0/PG_9.6_201607071/0/pgrn>
CONTEXT:  parallel worker
ERROR:  server conn crashed?
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
)
```

my postgres settings

```
max_parallel_workers_per_gather = 4
parallel_tuple_cost = 0
```

Seems like this bug dependent to new parallel sequence scan feature introduced in 9.6.

my docker-compose.yml
```
postgresqlmaster:
  image: postgres:9.6-beta3
  privileged: true
  environment:
    - POSTGRES_PASSWORD=database
    - POSTGRES_USER=database
    - POSTGRES_DB=database
  ports:
    - "5432:5432"
```

With postges 9.5 all is ok.
