### ISSUE TITLE
pgroonga case sensitive search for russian language

### ISSUE THREAD

**Issue by loktionovam** [pgroonga/pgroonga#92]
Hi,

The problem is that russian language search is case-sensitive, for example

- Launch Pgroonga via docker-compose
```yaml
version: '2'
services:
  PGroonga:
    image: groonga/pgroonga:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: PGroonga
      POSTGRES_PASSWORD: PGroonga
      POSTGRES_USER: PGroonga
```

- Create table as described in the tutorial

```sql
PGroonga=# create extension pgroonga;
CREATE EXTENSION
PGroonga=# CREATE TABLE memos (
PGroonga(#   id integer,
PGroonga(#   content text
PGroonga(# );
CREATE TABLE
PGroonga=# 
PGroonga=# CREATE INDEX pgroonga_content_index ON memos USING pgroonga (content);
CREATE INDEX
PGroonga=# INSERT INTO memos VALUES (1, 'Если');
INSERT 0 1
PGroonga=# INSERT INTO memos VALUES (2, 'если');
INSERT 0 1
PGroonga=# SET enable_seqscan = off;
SET
```

- Search for word ```если``` become case sensitive

```sql
PGroonga=# SELECT * FROM memos WHERE content &@ 'если';
 id | content 
----+---------
  2 | если
(1 row)

PGroonga=# SELECT * FROM memos WHERE content &@ 'Если';
 id | content 
----+---------
  1 | Если
(1 row)
```

- But search for word ```test``` case-insensitive

```sql
PGroonga=# INSERT INTO memos VALUES (3, 'Test');
INSERT 0 1
PGroonga=# INSERT INTO memos VALUES (4, 'test');
INSERT 0 1
PGroonga=# SELECT * FROM memos WHERE content &@ 'test';
 id | content 
----+---------
  3 | Test
  4 | test
(2 rows)
```
